/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netz.view;

/**
 *
 * @author horch
 */
public class ChatView extends javax.swing.JFrame
{


  /**
   * @return the btnSenden
   */
  public javax.swing.JButton getBtnSenden()
  {
    return btnSenden;
  }

  /**
   * @return the taTextAusgabe
   */
  public javax.swing.JTextArea getTaTextAusgabe()
  {
    return taTextAusgabe;
  }

  /**
   * @param taTextAusgabe the taTextAusgabe to set
   */
  public void setTaTextAusgabe(javax.swing.JTextArea taTextAusgabe)
  {
    this.taTextAusgabe = taTextAusgabe;
  }

  /**
   * @return the tfNachricht
   */
  public javax.swing.JTextField getTfNachricht()
  {
    return tfNachricht;
  }

  /**
   * @param tfNachricht the tfNachricht to set
   */
  public void setTfNachricht(javax.swing.JTextField tfNachricht)
  {
    this.tfNachricht = tfNachricht;
  }

  /**
   * Creates new form ChatView
   */
  public ChatView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spNachrichtenFeld = new javax.swing.JScrollPane();
        taTextAusgabe = new javax.swing.JTextArea();
        pnlPanel = new javax.swing.JPanel();
        tfNachricht = new javax.swing.JTextField();
        btnSenden = new javax.swing.JButton();
        pnlPanelOben = new javax.swing.JPanel();
        btnServer = new javax.swing.JButton();
        btnClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netzwerke");

        taTextAusgabe.setColumns(20);
        taTextAusgabe.setRows(5);
        spNachrichtenFeld.setViewportView(taTextAusgabe);

        getContentPane().add(spNachrichtenFeld, java.awt.BorderLayout.CENTER);

        tfNachricht.setPreferredSize(new java.awt.Dimension(300, 30));
        tfNachricht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNachrichtActionPerformed(evt);
            }
        });
        pnlPanel.add(tfNachricht);

        btnSenden.setText("Senden");
        pnlPanel.add(btnSenden);

        getContentPane().add(pnlPanel, java.awt.BorderLayout.PAGE_END);

        btnServer.setText("Server");
        btnServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerActionPerformed(evt);
            }
        });
        pnlPanelOben.add(btnServer);

        btnClient.setText("Client");
        pnlPanelOben.add(btnClient);

        getContentPane().add(pnlPanelOben, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void tfNachrichtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfNachrichtActionPerformed
  {//GEN-HEADEREND:event_tfNachrichtActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfNachrichtActionPerformed

  private void btnServerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnServerActionPerformed
  {//GEN-HEADEREND:event_btnServerActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnServerActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new ChatView().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnSenden;
    private javax.swing.JButton btnServer;
    private javax.swing.JPanel pnlPanel;
    private javax.swing.JPanel pnlPanelOben;
    private javax.swing.JScrollPane spNachrichtenFeld;
    private javax.swing.JTextArea taTextAusgabe;
    private javax.swing.JTextField tfNachricht;
    // End of variables declaration//GEN-END:variables

  /**
   * @return the btnClient
   */
  public javax.swing.JButton getBtnClient()
  {
    return btnClient;
  }

  /**
   * @return the btnServer
   */
  public javax.swing.JButton getBtnServer()
  {
    return btnServer;
  }
}
